# Generated by Django 5.1.1 on 2025-08-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_patrocinante', models.CharField(blank=True, max_length=255, null=True)),
                ('publicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('contenidos', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('fuentes', models.TextField(blank=True, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, max_length=255, null=True, upload_to='documentos/')),
                ('enlace_archivo', models.URLField(blank=True, max_length=500, null=True)),
                ('año', models.CharField(blank=True, max_length=4, null=True)),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('diseno', 'Diseño Tecnológico'), ('tecnologia', 'Tecnología')], default='electronica', max_length=50)),
                ('lineas_investigacion', models.ManyToManyField(blank=True, to='repositorio.lineainvestigacion')),
            ],
        ),
    ]
