# Generated by Django 5.1.1 on 2024-09-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudianteupn',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudianteupn',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudianteupn',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='trabajodegrado',
            name='EstudianteUPN',
        ),
        migrations.RemoveField(
            model_name='trabajodegrado',
            name='tutor',
        ),
        migrations.AddField(
            model_name='estudianteupn',
            name='codigo',
            field=models.CharField(default='NONE', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trabajodegrado',
            name='idautor',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='repositorio.estudianteupn'),
        ),
        migrations.AddField(
            model_name='trabajodegrado',
            name='lineaInv',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='trabajodegrado',
            name='metodologia',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='trabajodegrado',
            name='palabras_clave',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='trabajodegrado',
            name='titulo',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
