# Generated by Django 5.1.1 on 2025-08-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='enlace_archivo',
        ),
    ]
