# Generated by Django 5.1.1 on 2025-08-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_alter_documento_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
