# Generated by Django 5.1.1 on 2024-10-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0003_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='lineaInv',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='documento',
            name='resumen',
            field=models.TextField(default='No resumen disponible'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trabajodegrado',
        ),
    ]
