# Generated by Django 5.1.1 on 2024-10-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_documento_lineainv_documento_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='resumen',
            field=models.TextField(default='No resumen disponible'),
        ),
    ]
