# Generated by Django 5.1.1 on 2025-08-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_alter_documento_palabras_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='autor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='año',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='director',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='publicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='unidad_patrocinante',
            field=models.TextField(blank=True, null=True),
        ),
    ]
