# Generated by Django 5.1.1 on 2024-10-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0005_alter_documento_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='autor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='lineaInv',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resumen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.TextField(),
        ),
    ]
