# Generated by Django 5.1.1 on 2025-03-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0006_alter_documento_autor_alter_documento_lineainv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='lineaInv',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='resumen',
            new_name='fuentes',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Licenciatura en Electrónica'), ('diseno', 'Licenciatura en Diseño Tecnológico'), ('tecnologia', 'Licenciatura en Tecnología')], default='electronica', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='publicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
