# Generated by Django 5.1.1 on 2025-03-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0007_rename_lineainv_documento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(max_length=255, upload_to='documentos/'),
        ),
    ]
