# Generated by Django 5.1.1 on 2025-03-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0008_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conclusiones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
