# Generated by Django 5.1.1 on 2025-03-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0009_documento_conclusiones_documento_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documentos/'),
        ),
    ]
