# Generated by Django 5.1.1 on 2025-03-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0010_documento_enlace_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('diseno', 'Diseño Tecnológico'), ('tecnologia', 'Tecnología')], default='electronica', max_length=20),
        ),
    ]
