# Generated by Django 5.1.1 on 2025-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0011_alter_documento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='publicacion',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default=' ', upload_to='documentos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('electronica', 'Electrónica'), ('diseno', 'Diseño Tecnológico'), ('tecnologia', 'Tecnología')], default='electronica', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fuentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
