# Generated by Django 5.1.1 on 2025-03-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0012_remove_documento_publicacion_alter_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documentos/'),
        ),
    ]
