# Generated by Django 5.1.1 on 2025-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0013_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
