# Generated by Django 5.1.1 on 2025-03-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0014_documento_palabras_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_publicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='unidad_patrocinante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
