# Generated by Django 5.1.1 on 2025-03-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0015_documento_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='lineas_investigacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
