# Generated by Django 5.1.1 on 2025-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0016_documento_lineas_investigacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenidos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
