# Generated by Django 5.1.1 on 2025-07-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0017_documento_contenidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteUPN',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='fecha_publicacion',
            new_name='publicacion',
        ),
    ]
