# Generated by Django 5.1.1 on 2025-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0018_delete_estudianteupn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documento',
            name='lineas_investigacion',
        ),
        migrations.AddField(
            model_name='documento',
            name='lineas_investigacion',
            field=models.ManyToManyField(blank=True, to='repositorio.lineainvestigacion'),
        ),
    ]
