# Generated by Django 5.1.1 on 2025-07-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0019_lineainvestigacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='año',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='lineainvestigacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
