# Generated by Django 5.1.1 on 2025-07-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0020_documento_año_alter_lineainvestigacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enlace_archivo',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace al PDF (Cloudinary)'),
        ),
    ]
