# Generated by Django 5.1.1 on 2025-08-01 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0021_documento_enlace_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='enlace_archivo',
        ),
    ]
