# Generated by Django 5.1.1 on 2025-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0022_remove_documento_enlace_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
