# Generated by Django 5.1.1 on 2025-08-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0023_alter_documento_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enlace_archivo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
